Fix traceback reporting for assertion failures when inheriting from later.unittest.TestCase
Summary:
Given the following test cases, inheriting from default `unittest.TestCase` and `later.unittest.TestCase`:
```
import unittest
import later.unittest

class TestDefault(unittest.TestCase):
    def test1(self) -> None:
        self.assertFalse(True)

class TestLater(later.unittest.TestCase):
    def test1(self) -> None:
        self.assertFalse(True)
```

The default `unittest.TestCase` fails with good message, pointing to specific failed assertion line:
```
======================================================================
FAIL: test1 (sapienz.v2.view_ranking.tests.test_diff_targeting.TestDefault)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/akhmylov/fbsource/buck-out/v2/gen/fbcode/db57b53167ea1616/sapienz/v2/view_ranking/__diff_targeting_tests__/diff_targeting_tests#link-tree/sapienz/v2/view_ranking/tests/test_diff_targeting.py", line 103, in test1
    self.assertFalse(True)
AssertionError: True is not false
```

While `later.unittest.TestCase` fails non-informative error, not including the specific line which caused assertion failure:
```
======================================================================
FAIL: test1 (sapienz.v2.view_ranking.tests.test_diff_targeting.TestLater)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/akhmylov/fbsource/buck-out/v2/gen/fbcode/db57b53167ea1616/sapienz/v2/view_ranking/__diff_targeting_tests__/diff_targeting_tests#link-tree/later/unittest/case.py", line 216, in _callTestMethod
    super()._callTestMethod(testMethod)
AssertionError: True is not false
```

This is caused by `unittest/result.py/_clean_tracebacks` implementation https://github.com/python/cpython/blob/e42bda9441119c7952ada23e88e6f4ab79df86c2/Lib/unittest/result.py#L210, which tries to remove test frames and leave only user code frames, i.e. frames in between `unittest`, looking into the presence of `__unittest` in frame's globals.

A typical assertion traceback when using `unittest.TestCase` looks like:
```
unittest (runner)
--> unittest (case)
    --> specific test (our code)
        --> self.assert(...) call
            --> unittest internals to raise AssertionError
```

`_clean_tracebacks` helper leaves only `specific test (our code) --> self.assert(...) call` in that tree.

However, when we use `later.unittest.TestCase` inheriting from `unittest.TestCase`, the traceback looks like this:
```
unittest (runner)
--> unittest (case)
    --> later.unittest (case)
        --> unittest (via super()._callTestMethod() call)
            --> specific test (our code)
                --> self.assert(...) call
                    --> unittest internals to raise AssertionError
```

Walking from the top of the traceback and finding frames in between `unittest` results in `later.unittest (case)` only.

This diff adds `__unittest = True` global to `fbcode/later/unittest/case.py`, so that it's treated as a part of unit test infra and is correctly omitted from the traceback, resulting in more helpful assertion failure messages pointing to specific failed line.

Reviewed By: fried

Differential Revision: D73187440

fbshipit-source-id: 3d7e29548863ac40f9c4c29d933a6ae7e65733c7